services:
  backend:
    build: ./backend
    ports:
      - "3002:3001" # Adjusted port to match frontend calls
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/eva_edu"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/uploads:/usr/src/app/uploads # Persist uploads
      - /usr/src/app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3100:3000"
    environment:
      BACKEND_URL: "http://backend:3001/api"
    volumes:
      - /usr/src/app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eva_edu
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d eva_edu"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 